# Generated by Django 5.0.1 on 2024-01-13 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='height',
            field=models.SmallIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagedata',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.lesson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagedata',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/media/images/halfgreen_VSX6eUQ.png'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagedata',
            name='width',
            field=models.SmallIntegerField(default=100),
            preserve_default=False,
        ),
    ]
