# Generated by Django 5.0.1 on 2024-01-13 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_imagedata_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
    ]
