# Generated by Django 5.0.1 on 2024-01-14 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.chapter'),
            preserve_default=False,
        ),
    ]
